### ISSUE TITLE
Start postgres service before creating user and database

### ISSUE THREAD

**Issue by dennis531** [elan-ev/tobira-ansible-example#1]
I encountered the problem that the creation of the Postgres user failed because the service was inactive.

I fixed the problem in the db.yml by starting the service before creating the user:

```
# This is necessary for non-Debian systems (which use dnf or yum)
- name: initialize PostgreSQL
  command:
    cmd: postgresql-setup --initdb
    creates: /var/lib/pgsql/data/postgresql.conf
  environment:
    PGSETUP_INITDB_OPTIONS: "--auth-local=peer --auth-host=scram-sha-256"
  notify: restart postgresql

- name: start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create tobira postgres user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ tobira_db_user }}"
    password: "{{ tobira_db_password }}"

- name: create database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ tobira_db }}"
    owner: "{{ tobira_db_user }}"
```
